# Generated by Django 2.2.9 on 2022-01-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220111_1639'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Posts',
        ),
    ]
